const JobData = [
  {
      id: 1,
      job_name: 'Desenvolvedor Web',
      job_elapsed_time: 'Agora',
      job_city: 'Natal',
      job_description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius soluta atque ad quae consequatur labore magnam praesentium nihil, nulla, minima dolores animi deserunt magni, quod hic odio nobis neque velit!',
      job_company_name: "IFRN",
      job_company_image: "../src/assets/companies/ifrn.png",
      job_page_link: '#',
  },
  {
      id: 2,
      job_name: 'Desenvolvedor Backend',
      job_elapsed_time: 'Agora',
      job_city: 'Recife',
      job_description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius soluta atque ad quae consequatur labore magnam praesentium nihil, nulla, minima dolores animi deserunt magni, quod hic odio nobis neque velit!',
      job_company_name: "Meta",
      job_company_image: "../src/assets/companies/meta.png",
      job_page_link: '#',
  },
  {
      id: 3,
      job_name: 'Scrum Master',
      job_elapsed_time: 'Agora',
      job_city: 'São Paulo',
      job_description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius soluta atque ad quae consequatur labore magnam praesentium nihil, nulla, minima dolores animi deserunt magni, quod hic odio nobis neque velit!',
      job_company_name: "Shopify",
      job_company_image: "../src/assets/companies/shopify.png",
      job_page_link: '#',
  },
  {
      id: 4,
      
      job_elapsed_time: 'Agora',
      job_city: 'São Paulo',
      job_name: 'Desenvolvedor Frontend',
      job_description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius soluta atque ad quae consequatur labore magnam praesentium nihil, nulla, minima dolores animi deserunt magni, quod hic odio nobis neque velit!',
      job_company_name: "Starbucks",
      job_company_image: "../src/assets/companies/starbucks.png",
      job_page_link: '#',
  },
  {
      id: 5,
      job_name: 'Engenheiro de Software',
      job_elapsed_time: 'Agora',
      job_city: 'Rio de Janeiro',
      job_description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius soluta atque ad quae consequatur labore magnam praesentium nihil, nulla, minima dolores animi deserunt magni, quod hic odio nobis neque velit!',
      job_company_name: "Tesla",
      job_company_image: "../src/assets/companies/tesla.png",
      job_page_link: '#',
  },
]

export default JobData